name: fluttermessager
description: A messager aplication using Flutter and Firebase

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.4
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  fluttertoast: ^7.1.1
  shared_preferences: ^0.5.12
  cached_network_image: ^2.3.2+1
  intl: ^0.16.1
  firebase_messaging: 7.0.0
  flutter_local_notifications: 1.4.4+4
  photo_view: ^0.10.2
  image_picker: ^0.6.7+7
  flutter_launcher_icons: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "images/unicornio.png"

  assets:
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif